### Import standard GDAL and NumPy packages

In [5]:
import numpy as np
from osgeo import gdal

### Import SKOPE data analysis functions

In [6]:
import skope_analysis as sa

### Set the location and name of the data set file to create

In [7]:
test_dataset_filename = '../data/monthly_5x5x60_dataset_float32_variable.tif'

### Create the test dataset file using a local utility function

In [8]:
dataset = sa.create_dataset_file(
    filename     = test_dataset_filename,
    format       = 'GTiff',
    pixel_type   = gdal.GDT_Float32, 
    rows         = 5, 
    cols         = 5, 
    bands        = 60,
    origin_x     = -123,
    origin_y     = 45,
    pixel_width  = 1, 
    pixel_height = 1
)

### Define the pixel values to be assigned to the first band of the data set

In [9]:
nodata = -9999

band_1_data = np.array([
    [100, 101.1, 102.2, 103.3, 104.4],
    [110, 111.1, 112.2, 113.3, 114.4],
    [120, 121.1, 122.2, 123.3, 124.4],
    [130, 131.1, 132.2, 133.3, 134.4],
    [140, 141.1, 142.2, 143.3, 144.4]
])

### Write pixel values to each band of the data set
For all bands other than the first, the value of each pixel is 100 more than the pixel directly below it in the previous band.

In [10]:
for i in range(0,60):
    sa.write_band(
        dataset = dataset,
        band    = i + 1,
        array   = band_1_data + i * 100,
        nodata  = nodata
    )
    sa.write_pixel(dataset,band=i+1, row=3, column=4, value=nodata)

dataset.FlushCache()

### Confirm some expected pixel values in the new data set

In [11]:
assert sa.read_pixel(dataset,band=1,row=0,column=0) == 100
assert sa.read_pixel(dataset,band=1,row=4,column=4) - 144.4 < 0.00


#assert skope.gdal.read_pixel(dataset,band=60,row=0,column=0) == 6000
#assert skope.gdal.read_pixel(dataset,band=60,row=4,column=4) == 6044

### Display pixel values in each band of new data set for easy reference

In [12]:
for i in range(1,61):
    print("\nband", i, "\n", dataset.GetRasterBand(i).ReadAsArray())


band 1 
 [[  100.    101.1   102.2   103.3   104.4]
 [  110.    111.1   112.2   113.3   114.4]
 [  120.    121.1   122.2   123.3   124.4]
 [  130.    131.1   132.2   133.3 -9999. ]
 [  140.    141.1   142.2   143.3   144.4]]

band 2 
 [[  200.    201.1   202.2   203.3   204.4]
 [  210.    211.1   212.2   213.3   214.4]
 [  220.    221.1   222.2   223.3   224.4]
 [  230.    231.1   232.2   233.3 -9999. ]
 [  240.    241.1   242.2   243.3   244.4]]

band 3 
 [[  300.    301.1   302.2   303.3   304.4]
 [  310.    311.1   312.2   313.3   314.4]
 [  320.    321.1   322.2   323.3   324.4]
 [  330.    331.1   332.2   333.3 -9999. ]
 [  340.    341.1   342.2   343.3   344.4]]

band 4 
 [[  400.    401.1   402.2   403.3   404.4]
 [  410.    411.1   412.2   413.3   414.4]
 [  420.    421.1   422.2   423.3   424.4]
 [  430.    431.1   432.2   433.3 -9999. ]
 [  440.    441.1   442.2   443.3   444.4]]

band 5 
 [[  500.    501.1   502.2   503.3   504.4]
 [  510.    511.1   512.2   513.3   514.4]
