### Import standard GDAL and NumPy packages

In [1]:
import numpy as np
from osgeo import gdal

### Import SKOPE data analysis functions

In [2]:
import skope_analysis as sa

### Set the location and name of the data set file to create

In [3]:
test_dataset_filename = '../data/annual_5x5x5_dataset_uint16_variable.tif'

### Create the test dataset file using a local utility function

In [4]:
dataset = sa.create_dataset_file(
    filename     = test_dataset_filename,
    format       = 'GTiff',
    pixel_type   = gdal.GDT_UInt16, 
    rows         = 5, 
    cols         = 5, 
    bands        = 5,
    origin_x     = -123,
    origin_y     = 45,
    pixel_width  = 1, 
    pixel_height = 1
)

### Define the pixel values to be assigned to the first band of the data set

In [5]:
nodata = 65535

band_1_data = np.array([
    [100, 101, 102, 103, 104],
    [110, 111, 112, 113, 114],
    [120, 121, 122, 123, 124],
    [130, 131, 132, 133, 134],
    [140, 141, 142, 143, 144]
])

### Write pixel values to each band of the data set
For all bands other than the first, the value of each pixel is 100 more than the pixel directly below it in the previous band.

In [6]:
for i in range(0,5):
    sa.write_band(
        dataset = dataset,
        band    = i + 1,
        array   = band_1_data + i * 100,
        nodata  = nodata
    )
    sa.write_pixel(dataset,band=i+1,row=3,column=4,value=nodata)

sa.write_pixel(dataset,band=3,row=2,column=4,value=nodata)
    
dataset.FlushCache()

### Confirm some expected pixel values in the new data set

In [7]:
assert sa.read_pixel(dataset,band=1,row=0,column=0) == 100
assert sa.read_pixel(dataset,band=1,row=4,column=4) == 144
assert sa.read_pixel(dataset,band=1,row=3,column=4) == 65535
assert sa.read_pixel(dataset,band=2,row=3,column=4) == 65535
assert sa.read_pixel(dataset,band=3,row=3,column=4) == 65535
assert sa.read_pixel(dataset,band=4,row=3,column=4) == 65535
assert sa.read_pixel(dataset,band=5,row=3,column=4) == 65535
assert sa.read_pixel(dataset,band=3,row=2,column=4) == 65535

### Display pixel values in each band of new data set for easy reference

In [8]:
for i in range(1,6):
    print("\nband", i, "\n", dataset.GetRasterBand(i).ReadAsArray())


band 1 
 [[  100   101   102   103   104]
 [  110   111   112   113   114]
 [  120   121   122   123   124]
 [  130   131   132   133 65535]
 [  140   141   142   143   144]]

band 2 
 [[  200   201   202   203   204]
 [  210   211   212   213   214]
 [  220   221   222   223   224]
 [  230   231   232   233 65535]
 [  240   241   242   243   244]]

band 3 
 [[  300   301   302   303   304]
 [  310   311   312   313   314]
 [  320   321   322   323 65535]
 [  330   331   332   333 65535]
 [  340   341   342   343   344]]

band 4 
 [[  400   401   402   403   404]
 [  410   411   412   413   414]
 [  420   421   422   423   424]
 [  430   431   432   433 65535]
 [  440   441   442   443   444]]

band 5 
 [[  500   501   502   503   504]
 [  510   511   512   513   514]
 [  520   521   522   523   524]
 [  530   531   532   533 65535]
 [  540   541   542   543   544]]
